apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cinema.fullname" . }}
data:
  SECRET_KEY: {{ .Values.Django.SECRET_KEY | b64enc | quote }}
  DB_URL: {{ .Values.Django.DB_URL | b64enc | quote }}
