services:

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
    volumes:
      - cinema-db:/data/db
      
  cinema:
    container_name: cinema
    image: cinema
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      SECRET_KEY: $SECRET_KEY
      DEBUG: $DEBUG
      DB_NAME: $DB_NAME
      DB_URL: $DB_URL

# for local use
#    env_file:
#      - env-cinema 

    depends_on:
      - mongo
      
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    volumes:

      # for jenkins use
       - ./nginx.conf:/etc/nginx/

      # for local use
      #  - ./nginx.conf:/etc/nginx/nginx.conf 
      
       - ./cinema/static/:/usr/share/nginx/html/static
    ports:
      - 80:80
    depends_on:
      - mongo
      - cinema
    restart: always
 
volumes:
  cinema-db:
    name: cinema-db
    driver: local
