apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinema-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dawidtomczynski/cinema-gitops
    targetRevision: HEAD
    path: cinema-app/
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
