apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: "0.3.9"
    chart: fluentd
    helm:
      releaseName: fluentd
      values: |
        env:
        - name: "FLUENTD_CONF"
          value: "../../../etc/fluent/fluent.conf"
        - name: K8S_NODE_NAME 
          valueFrom: 
            fieldRef: 
              fieldPath: spec.nodeName 
        volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: etcfluentd-main
          configMap:
            name: fluentd-main
            defaultMode: 0777
        - name: etcfluentd-config
          configMap:
            name: fluentd-config
            defaultMode: 0777
        - name: elasticsearch-certs 
          secret: 
            secretName: elasticsearch-master-certs 
            defaultMode: 0777 
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: etcfluentd-main
          mountPath: /etc/fluent
        - name: etcfluentd-config
          mountPath: /etc/fluent/config.d/
        - name: elasticsearch-certs 
          mountPath: /certs/
        fileConfigs:
          04_outputs.conf: |-
            <label @OUTPUT>
              <match **>
                @type elasticsearch
                hosts "https://elastic:example@elasticsearch-master:9200"
                ssl_verify true 
                ca_file /certs/ca.crt
                client_crt /certs/tls.crt
                client_key /certs/tls.key
              </match>
            </label>
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      