apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "8.5.1"
    chart: kibana
    helm:
      releaseName: kibana
      parameters:
      - name: "service.type"
        value: "NodePort"
      values: |
        ingress:
          enabled: true
          className: "alb"
          pathtype: Prefix
          path: /
          hosts:
            - $KIBANA_DOMAIN
          tls: 
            - hosts:
                - $KIBANA_DOMAIN
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/certificate-arn: $KIBANA_ARN
            external-dns.alpha.kubernetes.io/hostname: $KIBANA_DOMAIN
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      
